[tools]
go = "1.25.5"
golangci-lint = "2.7.2"
gotestsum = "1.13.0"

# Internal
"go:github.com/project-init/devex/cmd/release" = "0.6.0"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true

# Tests

[tasks.test]
depends = [
    "unit-test"
]

[tasks.unit-test]
run = "gotestsum --format testname -- ./..."

# Linting

[tasks.lint]
run = "golangci-lint run --fix"

[tasks.format]
run = "go fmt ./..."
