[tools]
go = "1.25.5"
golangci-lint = "2.7.2"
gotestsum = "1.13.0"

[env]

[settings]
experimental = true

# Tests

[tasks.test]
depends = [
    "unit-test"
]

[tasks.unit-test]
run = "gotestsum --format testname -- ./..."

# Linting

[tasks.lint]
run = "golangci-lint run --fix"

[tasks.format]
run = "go fmt ./..."

# Release

[tasks.start-release]
run = "./scripts/git-tag-release.sh"
